### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by clem9669** [carlospolop/privilege-escalation-awesome-scripts-suite#10]
In the linpeas script, add a check to retrieve all *'look alike'* **hashes** (md5, sha, db hashes, etc)

**Comment by carlospolop** [comment]
Hi @clem9669,
Thank you very much for the suggestion. As soon as I can I will test the idea to see if in a "normal" scenario too much junk is listed or not.
Anyway, if you have a suggestion about how to code it, please let me know.

**Comment by clem9669** [comment]
Hi Carlos,
Thanks for the response :)
I thought I could be useful with the **-a** options for more advanced search on the server.

I imagine so far:

### MD5, MD4, Blake2b-128 and others 32 length hashes:
```bash
grep -RIE '[0-9a-f]{32}$' /home /etc # maybe good to change the path
```

### SHA0/1 and others:
```bash
grep -RIE '[0-9a-f]{40}$' /home /etc # maybe good to change the path
```

### SHAx-256, Keccak 256 and others:
```bash
grep -RIE '[0-9a-f]{64}$' / # maybe good to change the path
```

### SHAx-512, Keccak 512 and others:
``bash
grep -RIE '[0-9a-f]{128}$' / # maybe good to change the path
```

UPDATE:
After writing this comment, I saw that [https://www.unix-ninja.com/p/A_cheat-sheet_for_password_crackers](https://www.unix-ninja.com/p/A_cheat-sheet_for_password_crackers)

It has most interesting hashes (and more) in my opinion, this could nicely fit. 

What do you think ?

**Comment by carlospolop** [comment]
Hey @clem9669,
Thank you very much for the suggestions and the link, it was really useful!
Yeah, I think it would be better to start putting this option inside the **-a** behaviour.

Let me know what do you think about this approach:
```grep -RIPH "(^|[^a-zA-Z0-9])[a-fA-F0-9]{32}([^a-zA-Z0-9]|$)|(^|[^a-zA-Z0-9])[a-fA-F0-9]{40}([^a-zA-Z0-9]|$)|(^|[^a-zA-Z0-9])[a-fA-F0-9]{64}([^a-zA-Z0-9]|$)|(^|[^a-zA-Z0-9])[a-fA-F0-9]{128}([^a-zA-Z0-9]|$)" /etc /root /home 2>/dev/null | awk -F: '{if (pre != $1){ print $0; }; pre=$1}'```

This command is looking for hashes of length: 32 or 40 or 64 or 128 that are at the beginning of the line, at the end of the line or surrounded by symbols. Also, this `grep` will print the name of the file were the match was found and the `awk` will only allow to print 1 match per file.

**Comment by carlospolop** [comment]
Hello @clem9669,
At the end I decided to create 2 different checks: One that search specific hashes and another one that search more generic hashes. Please, take a look the new linpeas version (v2.9.9) and at the end of the code you can find these new checks.
Also, I would like to invite you to the telegram group I'm creating to talk about new features and fixes for all the tools inside the PEAS Suite, feel free to join: https://t.me/peass

**Comment by clem9669** [comment]
Hey
Thanks for your adds ! I am confident that will serve a lot :+1: 


Running it i found a problem on this part :

```bash
[+] Finding 'pwd' or 'passw' string inside /home, /var/www, /etc, /root and list possible web(/var/www) and config(/etc) passwords(limit 70)
head: cannot open '70' for reading: No such file or directory
```

Is it a problem on my side ? :bug:

**Comment by carlospolop** [comment]
Hey @clem9669,

That was my fault. I added and changed some limits and forgot to add the `-n` to the `head` command, it is fixed now.
Thank you very much for letting me know!
And if you find any other bug or have any other suggestion don't hesitate on letting me know using github issues or the telegram group!
