### ISSUE TITLE
Leyend instead of Legend

### ISSUE THREAD

**Issue by Draey** [carlospolop/privilege-escalation-awesome-scripts-suite#100]
In the legend section after a run of your compiled version of winpeas, the word legend is spelled wrong. Just thought you should know :)

**Comment by carlospolop** [comment]
Hi @Draey,

Thank you for letting me know.
Hopefully this week or next one winpeasv2 is going to be release and this issue is going to be fixed in that release.

**Comment by carlospolop** [comment]
Thanks mate. This is fixed now.
