### ISSUE TITLE
"Searching passwords in config PHP files" not finding "$password"

### ISSUE THREAD

**Issue by jackno** [carlospolop/privilege-escalation-awesome-scripts-suite#101]
When running the `linpeas.sh` script on a php web server, [PHP config files are searched but not properly grepped for password strings](https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/master/linPEAS/linpeas.sh#L2975).

Actual:
```bash
$ ./linpeas.sh
...
[+] Searching passwords in config PHP files
/var/www/html/configuration.php
...
```

Expected:
```bash
$ ./linpeas.sh
...
[+] Searching passwords in config PHP files
/var/www/html/configuration.php
	public $password = 'nv5uz9r3ZEDzVjNu';
```

Expected behavior would be for linpeas.sh to grep and print the `$password` variable in red highlighting.

**Comment by KatsuragiCSL** [comment]
It seems fixed now.

**Comment by carlospolop** [comment]
@jackno could you confirm is this is fixed?

**Comment by jackno** [comment]
looks like it's fixed, thanks
