### ISSUE TITLE
incrontab jobs not detected

### ISSUE THREAD

**Issue by bharder** [carlospolop/privilege-escalation-awesome-scripts-suite#103]
I recently worked on a machine that used incrontab to run a script.

A suggested feature for linpeas.sh is to run `incrontab -l` to see if there are any entries.

**Comment by KatsuragiCSL** [comment]
It seems not installed in most OS by default. Did linpeas.sh found incrond as a services?
If it did, I think we should view incrontab as a custom service which need to examine manually?

**Comment by carlospolop** [comment]
The check `incrontab -l` was added in the last commit: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/commit/036a2aed64efded7fef3a0b082ce001b5000013c
Thank you for the suggestion!
