### ISSUE TITLE
Winpeas binary no longer available

### ISSUE THREAD

**Issue by Zeecka** [carlospolop/privilege-escalation-awesome-scripts-suite#105]
Commit https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/commit/358b366408b7bc7a4cc531db67ab5034f60366b1 in #104 removed WinPeas binaries. 
Therefore, WinPeas can no longer be downloaded as a binary.

**Comment by carlospolop** [comment]
Thanks mate. This is fixed now.
