### ISSUE TITLE
Report Format Standard

### ISSUE THREAD

**Issue by supersexy** [carlospolop/privilege-escalation-awesome-scripts-suite#107]
Does exist any kind of Report Format Standard for the results that could be used for monitoring?

**Comment by carlospolop** [comment]
Hi @supersexy,
Nice nickname haha
I have plans to prepare some centralized service to launch and monitor the output of winpeas/linpeas creating web reports. However, it's not trivial to do and I don't have much free time atm.
Therefore I have added this issue to the Not top priority list.
If you want to help with this part of the project let me know and feel free to reopen the issue.

**Comment by PanwarM** [comment]
@carlospolop , can we discuss what is expected...as I am looking for something similar for my usage. 
On a high level, I expect that we gather the matrix data(linpeas data) and see any delta changes from last execution. 
Also, having a clear idea in terms of matrix of what is being gathered from linpeas/winpeas. We can also cross reference these with ATT&K threat models. But that's a different story.
