### ISSUE TITLE
Autologin Credentials (Linux)

### ISSUE THREAD

**Issue by unKn0wnUser453** [carlospolop/privilege-escalation-awesome-scripts-suite#108]
Add check for /etc/autologin credentials

Reference:
https://nixdoc.net/man-pages/IRIX/man1/sysadm/configAutoLogin.1.html

Location: /etc/autologin

If this file exists, the auto login feature is enabled.  The file contains the login name of the account that is automatically logged in at startup.  If this file does not exist, the auto login feature is disabled.

**Comment by bluecmd** [comment]
+1. A similar feature is also used in ChromeOS: https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/chromeos-base/autologin/files/init/autologin.conf

**Comment by carlospolop** [comment]
Hi guys, linpeas is now looking for `autologin` and `autologin.conf` files and will `cat` them if any is found in the last version.
If you feel this is not enough or you find any bug feel free to reopen this issue.
Thank you very much for the suggestion.

**Comment by bluecmd** [comment]
Thanks!

On https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/commit/3bf02fb0cbc9e9f063f48a92d04f093c169562d3#diff-39122aa0fe2c86237414bba8f426d228c5171d6031ecee9e921f6012f7049d99R2504 - should it be `dockerfiles` there? I might be missing where `autologinfiles` is being used.

**Comment by carlospolop** [comment]
Woow! Good one and pretty fast. That was definitely a bug, it should be now fixed, thanks!
