### ISSUE TITLE
Remove Spaces

### ISSUE THREAD

**Issue by unKn0wnUser453** [carlospolop/privilege-escalation-awesome-scripts-suite#109]
Should probably rename this path to not include spaces:
privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/binaries/Obfuscated Releases/

"Obfuscated Releases" >> "Obfuscated_Releases or Obfuscated-Releases

**Comment by carlospolop** [comment]
Hi mate, why is so?

**Comment by unKn0wnUser453** [comment]
Just makes things easier so you don't have to escape spaces. Just a suggestion not a thing you have to do.

**Comment by carlospolop** [comment]
Hi mate,
Thanks for the suggestion, but actually you don't even need to scape it, you can also use %20 or the plus symbol "+".
If there isn't any real advantage I don't think I will change it.
