### ISSUE TITLE
Wrong DNS

### ISSUE THREAD

**Issue by okazymyrov** [carlospolop/privilege-escalation-awesome-scripts-suite#115]
Hi,

`/dev/udp/1.11.1.1/53` should be `/dev/udp/1.1.1.1/53`.

https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/master/linPEAS/linpeas.sh#L1503

Br,
Oleksandr

**Comment by carlospolop** [comment]
Hi @okazymyrov,
Thanks you forletting me know, what a mistake!
This is now fixed, thanks!
