### ISSUE TITLE
Syntax error and/or fork: Cannot allocate memory

### ISSUE THREAD

**Issue by arnoldasr** [carlospolop/privilege-escalation-awesome-scripts-suite#116]
When running linpeas I get this error:

![image](https://user-images.githubusercontent.com/49907666/110616322-178e9180-819d-11eb-8f12-94ba4f6a0c9c.png)

if I run 
`-bash-4.2$ ./linpeas.sh -a -t 5`

 I get 

`Caching directories using  threads ./linpeas.sh: line 922: 1%: syntax error: operand expected (error token is "%")`

Maybe there is something finicky happening? Let me know if I need to provide more details:

**Comment by carlospolop** [comment]
Hi @arnoldasr,

Thats weird, where are you running linpeas?
Inside a `sh` session can you execute:
```bash
CONT_THREADS=2
THREADS=5
echo "$(($CONT_THREADS%$THREADS))"
```
and let me know the result?

can you also run linpeas with 1 thread and check if any error appears?

**Comment by arnoldasr** [comment]
With a single thread, I get the same result.

![image](https://user-images.githubusercontent.com/49907666/110622699-79062e80-81a4-11eb-9d83-1fa5a02f90a3.png)

The same problem persists on a cpanel server and on a generic shared server.

**Comment by carlospolop** [comment]
Okay ate, could you specify in which case you get the error `cannot allocate memory` and in which one `Caching directories using threads ./linpeas.sh: line 922: 1%: syntax error: operand expected (error token is "%")` ?

Also, you have execute that code inside  a bash shell, could you try it in a `sh` shell?

Moreover, could you try to execute linpeas using bash: `bash linpeas.sh`?

**Comment by arnoldasr** [comment]
When I run `sh linpeas.sh` I get 

```bash
Caching directories using 40 threads linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
-bash-4.2$ linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
```
when I run  `bash linepas.sh`

I get

```bash
Caching directories using 40 threads linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
-bash-4.2$ linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
linpeas.sh: fork: Cannot allocate memory
```

When I run 

`bash linpeas.sh -t 1` it works

When I run 

`./linpeas.sh -t 1`

I get

`Caching directories using  threads ./linpeas.sh: line 922: 1%: syntax error: operand expected (error token is "%")`

When I run `-bash-4.2$  sh linpeas.sh -t 1`

I get 

`Caching directories using  threads linpeas.sh: line 922: 1%: syntax error: operand expected (error token is "%")` 

This is very strange to be honest

**Comment by carlospolop** [comment]
Hi mate!
The issue `syntax error: operand expected (error token is "%")` should be fixed in the latest version.
About `Cannot allocate memory` it's probably fault of using so many thread, so now the problem with `-t` is solved you should be able to lower the number of threads.
Let me kno if thats the case to close the issue.

**Comment by arnoldasr** [comment]
Hi there!

You are the best, now it works as intended, I wish you a happy week ahead!
