### ISSUE TITLE
Something wrong  Readable files inside backup folders

### ISSUE THREAD

**Issue by francoataffarel** [carlospolop/privilege-escalation-awesome-scripts-suite#117]
https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/4d69dc6e6cc4b476aeadaa118804acada1f29c48/linPEAS/linpeas.sh#L2961

Hello, @carlospolop i realize that linpeas cannot show up backup folders like /var/backups. Looks like that something wrong when script will put  $backup_folders_row  variable in find send null valor.

can u check?

to see is simple run inside **thenotebook** **hackthebox** box, the script cannot show file home.tar.gz.

i got this file change this line

 filstmpback=`find /tmp /var/tmp /private/tmp /private/var/at/tmp /private/var/tmp $backup_folders_row -type f 2>/dev/null | head -n 70`

for 

filstmpback=`find /tmp /var/tmp /private/tmp /private/var/at/tmp /private/var/tmp /var/backups -type f 2>/dev/null | head -n 70`

**Comment by carlospolop** [comment]
This should be now fixed, Thank you very much for reporting the issue!
