### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by kronikpillow** [carlospolop/privilege-escalation-awesome-scripts-suite#120]
hey guys ... first time bumped in to this, thx to Chris Titus youtube video ... ran the tool and I'm confused about this ...

`Hostname: Writable folder: /.snapshots/18/snapshot/var/spool/mail`

on his video the Hostname: Writable folder points to /dev/shm ... while on my system it keeps pointing to my btrfs snapshots, in a location inside of the snapshot ... even after deleting all snapshots, it just starts pointing to the next one that is automatically created ... 

I'v been trying to find out what Hostname: Writable folder actually means and why it's pointing to where it's pointing ... but I had no luck with it ...

can someone be kind enough to elaborate what this is??

**Comment by carlospolop** [comment]
Hi mate,

Linpeas just shows the first writable folder path found
