### ISSUE TITLE
Exes are getting caught by windows AV just after installing

### ISSUE THREAD

**Issue by randomUser7852** [carlospolop/privilege-escalation-awesome-scripts-suite#121]
Hi, 

Your exe is getting caught, but your script is fine, should I try to run it and find a way to obfuscate the exe or it create the same output than the batch?

**Comment by carlospolop** [comment]
Hi mate,
The exe has more checks than the batch.
In the Readme of the exe you can find how to execute it from memory and how to compile you own obfuscated version, that should be enough to bypass the AV.
