### ISSUE TITLE
Linpeas SUID searching

### ISSUE THREAD

**Issue by A1vinSmith** [carlospolop/privilege-escalation-awesome-scripts-suite#126]
Any thoughts on making difference between default and non-default binaries color?
Like default remain green? and non-default binaries color can be yellow?
It'll real nice if that can be distinguished.

**Comment by A1vinSmith** [comment]
I can make the PR if that's an option

**Comment by A1vinSmith** [comment]
```
[#] Finding/Listing all SUID Binaries ..
[!] Default Binaries (Don't bother)
------------------------------
/bin/umount
/bin/fusermount
/bin/su
/bin/mount
/bin/ping
/bin/ping6
/sbin/mount.nfs
/usr/bin/gpasswd
/usr/bin/traceroute6.iputils
/usr/bin/sudo
/usr/bin/arping
/usr/bin/at
/usr/bin/newgrp
/usr/bin/chfn
/usr/bin/chsh
/usr/bin/passwd
/usr/sbin/pppd
/usr/lib/eject/dmcrypt-get-device
/usr/lib/openssh/ssh-keysign
------------------------------

[~] Custom SUID Binaries (Interesting Stuff)
------------------------------
/lib/dhcp3-client/call-dhclient-script
/usr/bin/sudoedit
```

**Comment by clem9669** [comment]
Hey, seems nice idea! 
Why not adding a SGID too 😉 

Typo: [!] Default Binaries (Don't bother **too much**) 😄

**Comment by carlospolop** [comment]
Hi guys,

Sounds good, please send a PR and I will review it. Instead of yellow for third party suid binaries without known vulnerabilities I would suggest to use cyan (it's already used in other parts of the script) as it also looks like something benign.
Also, feel free to check new SUID privilege escalations of the default and custom suid binaries and add them to the PR if you wish.

**Comment by A1vinSmith** [comment]
<img width="1159" alt="Screen Shot 2021-05-01 at 3 50 52 PM" src="https://user-images.githubusercontent.com/24937594/116775866-8ad7c400-aab9-11eb-8baa-741a2894e9a6.png">

`sudo` now has been counted as default/normal binary.
custom binary shows as cyan now

**Comment by carlospolop** [comment]
merged!
