### ISSUE TITLE
PayPal is broken

### ISSUE THREAD

**Issue by AbelLykens** [carlospolop/privilege-escalation-awesome-scripts-suite#15]
> PayPal cannot process this transaction because of a problem with the seller's website. Please contact the seller directly to resolve this problem.

After clicking the button. FYI.

**Comment by carlospolop** [comment]
Hello @AbelLykens,

Thanks for trying to donate, please let me know exactly in which link donate you clicked.
I've asked a friend to use the main link in https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite to donate and it worked for him.

**Comment by AbelLykens** [comment]
Hmm the one on winpeas works (now). It was in Spanish [?] though, but the colors of the buttons helped me. Cheers, you were very helpful for OSCP yesterday.
