### ISSUE TITLE
winPEAS.bat no longer working properly

### ISSUE THREAD

**Issue by zomfg-zombie** [carlospolop/privilege-escalation-awesome-scripts-suite#160]
I've attempted to use winPEAS.bat on multiple Windows 10 hosts and found the script would repeat checks until cancelled. 

The last working version I've used is commit 256b22d0dcac8d027027d4455b251dc48ff20215. Versions after the re-write on October 9th 2020 no longer function as intended, at least for me.

**Comment by zoork11** [comment]
Can you check if all the line endings in your batch are in windows style? Might be the problem, this should be fixed by the .gitattributes file but the settings can be overwritten or maybe you have local changes on the batch.

**Comment by makikvues** [comment]
first of all, thank you for reporting the issue.
Could you please provide a redacted log or some more details? e.g. after which check it starts to repeat? 
Can you also confirm you don't have any local changes?
You could double check the EOL type e.g. in notepad++ -> Edit -> EOL Conversion
My tests are showing that the latest version of winpeas.bat is working properly.
Thanks :)

**Comment by zomfg-zombie** [comment]
This is what I get for trying to just download the .bat file. Worked perfectly after cloning the repo...

Can't believe line endings are still causing me grief in 2021. 

Thanks for the help, and sorry for the waste of time!
