### ISSUE TITLE
Colors don't display in powershell

### ISSUE THREAD

**Issue by jedai47** [carlospolop/privilege-escalation-awesome-scripts-suite#165]
Hi
I do not really understand why but colors dont display in my powershell session. But when i am using the one liner powershell that download and execute it displays colors. 
Thanks for the help
![colorwinpeas](https://user-images.githubusercontent.com/47899257/124038034-cbdc4e00-da00-11eb-9898-5d9187dbb41a.PNG)

**Comment by makikvues** [comment]
hello, please add a registry key with:
REG ADD HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1
and open a new terminal, the colors should work
