### ISSUE TITLE
System.Runtime.InteropServices.COMException: The handle is invalid. 

### ISSUE THREAD

**Issue by stock99** [carlospolop/privilege-escalation-awesome-scripts-suite#17]
got the following error when running the obfus version of winpeas (winPEASx64.exe).  The error occurs when it is enumerating the "processes information".  
==================error message================
Unhandled Exception: System.Runtime.InteropServices.COMException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
   at winPEAS.SamServer.c.d(Boolean A_0)
   at winPEAS.SamServer.c.Finalize()

if running 64 bit winpeas, the error message is slightly different. 
c:\scripts\privesc\config checking\peas>winPEAS.exe notcolor > output4.txt

Unhandled Exception: System.Runtime.InteropServices.COMException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
   at winPEAS.SamServer.UNICODE_STRING.Dispose(Boolean disposing)
   at winPEAS.SamServer.UNICODE_STRING.Finalize()

===========
windows 10 64bits version:
Microsoft Windows [Version 10.0.17763.1039]

by the way, I did some change of the system by installing the batch script for practicing privesc 
 which shouldn't cause the issue.. https://github.com/sagishahar/lpeworkshop/blob/master/lpe_windows_setup.bat

**Comment by carlospolop** [comment]
Hi @stock99,

Sorry for the waiting, these have been some busy days.
I have seen this error before during my tests, but it appeared to be kind of random. It appeared after executing winpeas several times and if I rebooted the machine or wait some minutes it disappeared. Even, some times, executing winpeas several times without any waiting the error didn't appear. So I haven't been able to debug it.
In your case, does the error appear every time? Even after a reboot? Have you tried to compile winpeas yourself and execute it?

As you said, that script shouldn't cause any issue, but I will try to recreate the environment.

In any case, during the next update at least I will catch the exception so winpeas doesn't die because of this error, and I will also try to find why the error is caused.

**Comment by stock99** [comment]
HI,
I forgot to turn off my windows update on the vm, and now it is updated to latest patches. One minor difference is that color is now correctly displayed.  I reboot the machine and still get the same error message.  I use the binary from your github link.  Haven't tried compiled it myself yet...But if this make issue goes away, it probably not going to help when privesc actual target (where i can't always compile things there...).  Skip the error to make program keep going certainly help alot.   By the way, if there is a way to make batch version display color that would be real cool. 

Below is the error message.. similar error message. 
Unhandled Exception: System.Runtime.InteropServices.COMException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
   at winPEAS.SamServer.c.d(Boolean A_0)
   at winPEAS.SamServer.c.Finalize()

**Comment by carlospolop** [comment]
Yeah, I completely agree, the binary should work on any machine, but maybe if you can compile it in that machine we could more easily know what is actually happening.
During my tests I have seen that error when trying to get the password policy and when trying to get the running processes, could you let me know in which exact check are you having the error?

Regarding the colours of winpeas.bat, I also agree that would be very cool. It is possible, but it will take several hours and an a .bat is not very stealthy (so I think that most of the people uses winpeas.exe). I haven't planned that update for anytime soon but I will keep it in mind, let me know if you want to help with that task.

**Comment by stock99** [comment]
did a quick compile and got the same error message(see below).  I didn't use any flag/option. just run  .\winPEAS.exe.   If you install the setup file from privesc workshop, maybe you can reproduce the error (just random guess here). 

  ========================================(Services Information)========================================

  [+] Interesting Services -non Microsoft-(T1007)
   [?] Check if you can overwrite some service binary or perform a DLL hijacking, also cehck for unquoted paths https://book.hacktricks.xyz/windows/windows-local-privilege-escalation#services

Unhandled Exception: System.Runtime.InteropServices.COMException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
   at winPEAS.SamServer.UNICODE_STRING.Dispose(Boolean disposing) in C:\Users\stock99\Documents\peas_test\privilege-escalation-awesome-scripts-suite-master\winPEAS\winPEASexe\winPEAS\UserInfo.cs:line 221
   at winPEAS.SamServer.UNICODE_STRING.Finalize() in C:\Users\stock99\Documents\peas_test\privilege-escalation-awesome-scripts-suite-master\winPEAS\winPEASexe\winPEAS\UserInfo.cs:line 226

**Comment by carlospolop** [comment]
Hi @stock99 ,
I think that this problem is fixed in the new version.
Please, check the latest version and reopen the issue if the problem still persists. 
Also, thank you for notifying the bug.
I would like to invite you to the telegram [PEASS group](https://t.me/peass) for commenting future bugs/improvements faster.
