### ISSUE TITLE
Add Powershell Transcript file's monitor

### ISSUE THREAD

**Issue by alegrey91** [carlospolop/privilege-escalation-awesome-scripts-suite#22]
Hi! I recently used the awesome **winPEAS** on htb.
I think this could be improved by adding this simple feature to monitor interesting Powershell Transcript files located under `C:\transcripts\`.
What do you think about?

**Comment by carlospolop** [comment]
Hi @alegrey91,

Thanks for your suggestion. I understand that your purpose is to list the `C:\transcripts\` directory to see if there is any powershell history, right?
It is a very good idea, I will add in my TODO list for the next winpeas release.
Thank you!

**Comment by carlospolop** [comment]
Hey @alegrey91,

I didn't forget about you, you can find a new winpeas release with this check added.
Enjoy it and thank you for the suggestion!

**Comment by alegrey91** [comment]
That's amazing @carlospolop. Thanks for your precious work.
