### ISSUE TITLE
'RED' as well as other highlighting not showing up in Konsole

### ISSUE THREAD

**Issue by stefanman125** [carlospolop/privilege-escalation-awesome-scripts-suite#24]
![image](https://user-images.githubusercontent.com/38778523/77260846-c5d5ba00-6c60-11ea-9d69-b5ac9dde0386.png)
The text at the bottom ("Private SSH keys found!:" and below) should be highlighted RED, not bolded.

**Comment by carlospolop** [comment]
Hi @stefanman125,

Thank you for letting me know this bug.
As you may see in: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/044d0ddc0d9746d0206e84eb82df9df5d08b7f91/linPEAS/linpeas.sh#L1232

The that information is coloured using the ansi code for RED (31), so I don't why know that is't working in Konsole.
Is that the only part of the output that should be coloured in RED but instead is just bolded in Konsole? Do you have any thoughts about why is this happening?

**Comment by stefanman125** [comment]
Hey @carlospolop 

That isn't the only part, every section that is supposed to be highlighted red is bolded. My only idea is that Konsole's appearance profile is changing the red. If I run the same script in xterm, it shows up red as expected. 

In Konsole's appearance settings, I changed my current appearance (Blue on Black) to the other ones, and the RED part just stayed blue.

**Comment by carlospolop** [comment]
So, it appears that this is a Konsoles problem, I don't think that I can do anything.
Feel free to reopen the issue if you think that anything can be done.

Thank you anyway for letting me know this possible issue!
