### ISSUE TITLE
[Feature REQUEST] Look for DNS Admin Server Level DLL Injection - winPEAS

### ISSUE THREAD

**Issue by guanicoe** [carlospolop/privilege-escalation-awesome-scripts-suite#27]
Hi, I just did a box on HackTheBox, and I had to use DNSAdmins to Domain Admins - Server Level DLL Injection  (http://www.abhizer.com/windows-privilege-escalation-dnsadmin-to-domaincontroller/) Apparently a vulnerable box can be detected if the user is part of the DNSAdmin group. Could winPEAS be able to detect this?

**Comment by carlospolop** [comment]
Hi @guanicoe,

Thank for the suggestion. I have added this here: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/752b8f0a672feee3d8db17d21fc7c417e2658a96/winPEAS/winPEASexe/winPEAS/Program.cs#L23

In the next release DNSAdmins group should be detected.
Thanks.

**Comment by guanicoe** [comment]
Fantastic! thanks
