### ISSUE TITLE
Output is very messy in my powershell

### ISSUE THREAD

**Issue by mpgn** [carlospolop/privilege-escalation-awesome-scripts-suite#28]
The default output when I launch the exe in my powershell console

![image](https://user-images.githubusercontent.com/5891788/78459491-9a6bba00-76b9-11ea-9008-32abe5f75a67.png)

How can I fix this ?

**Comment by elc0rr3Km1n0s** [comment]
Hi, same issue here from cmd prompt 
![screenshot_2020-04-04_21-34](https://user-images.githubusercontent.com/13037197/78459822-1cf57900-76bc-11ea-9d9b-ceed7d515a2f.png)

**Comment by carlospolop** [comment]
Hello guys!

If you take a look to the Readme a of Winpeas (exe) you will see this:
![image](https://user-images.githubusercontent.com/17181413/78536912-78bc2100-77e6-11ea-9df1-64e5d91f4e90.png)

Also notice that when you execute winpeas.exe, the very first line will indicate you to run the same command if the colours aren't enabled in your system.

Please, feel free to reopen this issue if this doesn't fix your problem.
