### ISSUE TITLE
Versión 64bits para w10 da problemas.

### ISSUE THREAD

**Issue by juancar1979** [carlospolop/privilege-escalation-awesome-scripts-suite#3]
Buenas!

Me bajé la versión compilada de winPEAS para 65bits y me aparece"no se puede iniciar o ejecutar porque no es compatible con versiones de 64 bits de windows...".

Utilizo un W10, alguién tiene alguna idea?

Muchas gracias!

Un saludo,

**Comment by carlospolop** [comment]
Hola juancar,

Muchas gracias por compartir el error que te da.
Probablemente la mejor solución rapida para este problema es que intentes compilarlo en tu equipo porque seguramente no tendremos la misma version de Windows.

De todas formas en cuanto tenga tiempo le echaré un ojo a ver si encuentro alguna solición mejor, dejo el issue abierto mientras.

**Comment by juancar1979** [comment]
Gracias!!! me dá un problema en la compilación... no sé si te lo habrás encontrado:
Gracias!!!

""c:\winPEAS\winPEASexe\winPEAS.sln" (destino predeterminado) (1) ->
"c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj" (destino predeterminado) (2) ->
(CoreCompile destino) ->
  ApplicationInfo.cs(130,14): error CS1513: Se esperaba } [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  ApplicationInfo.cs(161,17): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPE
AS\winPEAS.csproj]
  ApplicationInfo.cs(161,64): error CS1001: Se esperaba un identificador [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  ApplicationInfo.cs(163,13): error CS0116: Un espacio de nombres no puede contener directamente miembros como campos o
 métodos [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  ApplicationInfo.cs(170,5): error CS1022: Se esperaba una definición de tipo o espacio de nombres, o el fin del archiv
o [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  ApplicationInfo.cs(171,1): error CS1022: Se esperaba una definición de tipo o espacio de nombres, o el fin del archiv
o [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  KnownFileCredsInfo.cs(515,46): error CS1008: Se esperaba el tipo byte, sbyte, short, ushort, int, uint, long o ulong
[c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  KnownFileCredsInfo.cs(534,51): error CS1008: Se esperaba el tipo byte, sbyte, short, ushort, int, uint, long o ulong
[c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  KnownFileCredsInfo.cs(1738,50): error CS1008: Se esperaba el tipo byte, sbyte, short, ushort, int, uint, long o ulong
 [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  KnownFileCredsInfo.cs(1853,43): error CS1008: Se esperaba el tipo byte, sbyte, short, ushort, int, uint, long o ulong
 [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  KnownFileCredsInfo.cs(1880,44): error CS1008: Se esperaba el tipo byte, sbyte, short, ushort, int, uint, long o ulong
 [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  KnownFileCredsInfo.cs(1909,41): error CS1008: Se esperaba el tipo byte, sbyte, short, ushort, int, uint, long o ulong
 [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(68,10): error CS1513: Se esperaba } [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(360,32): error CS1519: El token '(' no es válido en una clase, struct o declaración de miembro de interfaz
 [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(361,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(362,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(363,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(364,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(365,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(366,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(367,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(368,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(369,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(370,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(371,13): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPE
AS.csproj]
  Program.cs(379,24): error CS1518: Se esperaba una clase, un delegado, una enumeración, una interfaz o un struct [c:\w
inPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(396,50): error CS1518: Se esperaba una clase, un delegado, una enumeración, una interfaz o un struct [c:\w
inPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(418,13): error CS0116: Un espacio de nombres no puede contener directamente miembros como campos o métodos
 [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(420,28): error CS1518: Se esperaba una clase, un delegado, una enumeración, una interfaz o un struct [c:\w
inPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Program.cs(432,13): error CS1022: Se esperaba una definición de tipo o espacio de nombres, o el fin del archivo [c:\w
inPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  UserInfo.cs(214,47): error CS1002: Se esperaba ; [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  UserInfo.cs(214,57): error CS1519: El token '!=' no es válido en una clase, struct o declaración de miembro de interf
az [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  UserInfo.cs(214,103): error CS1001: Se esperaba un identificador [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  UserInfo.cs(214,105): error CS1002: Se esperaba ; [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  UserInfo.cs(225,31): error CS1002: Se esperaba ; [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  UserInfo.cs(225,34): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winP
EAS.csproj]
  UserInfo.cs(225,42): error CS1031: Se esperaba un tipo [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(79,38): error CS1002: Se esperaba ; [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(80,13): error CS1519: El token '=>' no es válido en una clase, struct o declaración de miembro de interfaz
[c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(80,27): error CS1519: El token '=' no es válido en una clase, struct o declaración de miembro de interfaz [
c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(91,47): error CS1002: Se esperaba ; [c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(92,13): error CS1519: El token '=>' no es válido en una clase, struct o declaración de miembro de interfaz
[c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(92,38): error CS1519: El token '(' no es válido en una clase, struct o declaración de miembro de interfaz [
c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(92,41): error CS1519: El token '=>' no es válido en una clase, struct o declaración de miembro de interfaz
[c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(92,61): error CS1519: El token '==' no es válido en una clase, struct o declaración de miembro de interfaz
[c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(92,66): error CS1519: El token ')' no es válido en una clase, struct o declaración de miembro de interfaz [
c:\winPEAS\winPEASexe\winPEAS\winPEAS.csproj]
  Watson.cs(92,68): error CS1520: El método debe tener un tipo de valor devuelto [c:\winPEAS\winPEASexe\winPEAS\winPEAS
.csproj]

    4 Advertencia(s)
    47 Errores"

**Comment by juancar1979** [comment]
Ahora mismo no me aparece nada cuando ejecuto, se queda como en ejecución... :S

**Comment by juancar1979** [comment]
La compilación me da error, no sabrías porque puede ser? (adjunto error) Gracias!!!
[winpeas_comp_error1.txt](https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/files/3830823/winpeas_comp_error1.txt)

**Comment by carlospolop** [comment]
Hola Juancar,

Si se ejecuta sin tirar ningún error puedes dejarlo corriendo unos cuantos minutos? es posible que tarde un poco en empezar a salir output por la creación de listas dinámicas que luego servirán para colorear la salida.
Por la salida de errores catastróficos que me has compartido no sabría decirte qué es porque da la sensación de que nada funciona bien. He compilado winpeas del proyecto directamente descargado de la última versión de winpeas y me compila bien en dos hosts con Windows y en varias máquinas virtuales, además he pedido a más gente que lo pruebe y tampoco han tenido ningún problema, así que el error debe de estar en tu setup.

Puedes confirmarme que estas usando .Netv4 en Visual Studio 2019 y en un Windows 10? Este sería el caso ideal donde no te debería de fallar (aunque en otros también debería funcionar)

**Comment by juancar1979** [comment]
Buenas Carlos!
Muchas gracias! he hecho la compilación con .Netv4 en Visual Studio 2019 y W10 y todo perfecto, pero al ejectuar se me queda  frito...
![winpeas](https://user-images.githubusercontent.com/5212618/68762818-3f0c3300-0617-11ea-93df-776b70f6b7ff.png)

 A ver si encuentro la razón. Muchas gracias por todo!

**Comment by carlospolop** [comment]
Me alegro de que ya te funcione, si no sale nada probablemente no es que se quede frito, sino que anda intentando sacar info sobre usuarios del cotrolador de dominio.
Por favor asegúrate de que estas usando la última versión de winpeas (en el último commit retoqué unas cosas para que fuese mejor) y pruébalo otra vez. De todas formas si tarda mucho en empezar a salir output, por favor escríbime por telegram a @pcnick y miramos en detalle qué pasa exactamente.

Cierro el issue porque ya te funciona, pero si tarda mucho en salir output acuérdate de escribirme, winpeas aún esta en versión beta por cosas como estas.
Muchas gracias por compartir tu problema con winpeas.
