### ISSUE TITLE
Windows defender

### ISSUE THREAD

**Issue by Dexy2811** [carlospolop/privilege-escalation-awesome-scripts-suite#32]
Peass is detected by windows defender still chrome, firefox, ms edge all blocked download and if i allowed download defender removed it becouse it "contained a virus"

**Comment by carlospolop** [comment]
Hi @Dexy2811,

Just to be sure, are you downloading the obfuscated releases? (from here https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/tree/master/winPEAS/winPEASexe/winPEAS/bin/Obfuscated%20Releases)

**Comment by Dexy2811** [comment]
Yes i did download the obfuscated version but was blocked from downloading it. @carlospolop

**Comment by carlospolop** [comment]
Ok,

I'm afraid I don't have plans to support updated antivirus bypass neither for Winpeas nor Linpeas (like most of the tools whose goal isn't the bypass of an AV).
I just could suggest you to compile your own obfuscated version, prepare you own VPS (or just your main host) with a web server serving your compiled versions, and try to download them from there.
If does doesn't work, check for other alternatives like using other AV bypasses of executing Winpeas from memory.
Please, if you find a way to bypass these AVs, comment it here so other people can read it and share other techniques.
Thank you @Dexy2811
