### ISSUE TITLE
Wrong color highlight in version v2.4.5

### ISSUE THREAD

**Issue by dmknght** [carlospolop/privilege-escalation-awesome-scripts-suite#38]
![Screenshot at 2020-04-21 19-58-27](https://user-images.githubusercontent.com/29118926/79868717-da2be480-83cf-11ea-8c35-81f9d87f9568.png)

![Screenshot at 2020-04-21 20-05-57](https://user-images.githubusercontent.com/29118926/79869436-dfd5fa00-83d0-11ea-905e-14699c0b6bb7.png)
![Screenshot at 2020-04-21 20-06-04](https://user-images.githubusercontent.com/29118926/79869441-e3698100-83d0-11ea-8716-ca94fba71f87.png)

**Comment by carlospolop** [comment]
In my test environment this looks good:
![image](https://user-images.githubusercontent.com/17181413/79868954-97bad580-83d8-11ea-8cd4-561b84fd4929.png)

What is the value of your $PATH env variable? Was this happening before the other issue?

**Comment by dmknght** [comment]
My path: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dmknght/.local/bin:/snap/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
This is new version. I need to edit the screenshot because there is 1 more screenshot

**Comment by dmknght** [comment]
> In my test environment this looks good:
> ![image](https://user-images.githubusercontent.com/17181413/79868954-97bad580-83d8-11ea-8cd4-561b84fd4929.png)
> 
> What is the value of your $PATH env variable? Was this happening before the other issue?

I've added more screenshots

**Comment by carlospolop** [comment]
I need you to execute this and give me the output:
```
SEDOVERFLOW=true
while $SEDOVERFLOW; do
  WF=`find /dev /srv /proc /home /media /sys /lost+found /run /etc /root /var /tmp /mnt /boot /opt -type d -maxdepth $MAXPATH_FIND_W -writable 2>/dev/null | sort`
  Wfolders=`echo $WF | tr ' ' '|' | sed 's/|/\\\|/g'`"\|[^\*]\ \*"
  printf "test\ntest\ntest\ntest"| sed "s,$Wfolders\|\./\|\.:\|:\.,${C}[1;31;103m&${C}[0m,g" >/dev/null 2>&1
  if [ $? -eq 0 ]; then
      SEDOVERFLOW=false
  else
      MAXPATH_FIND_W=$(($MAXPATH_FIND_W-1)) #If overflow of directories, check again with MAXPATH_FIND_W - 1
      echo "Testing $MAXPATH_FIND_W"
  fi
done
echo $WF
echo "========================================================="
echo $Wfolders
```

Also the new pics are really weird, could you try to reboot your system, redownload the new version and try again? xD

**Comment by dmknght** [comment]
> I need you to execute this and give me the output:
> 
> ```
> SEDOVERFLOW=true
> while $SEDOVERFLOW; do
>   WF=`find /dev /srv /proc /home /media /sys /lost+found /run /etc /root /var /tmp /mnt /boot /opt -type d -maxdepth $MAXPATH_FIND_W -writable 2>/dev/null | sort`
>   Wfolders=`echo $WF | tr ' ' '|' | sed 's/|/\\\|/g'`"\|[^\*]\ \*"
>   printf "test\ntest\ntest\ntest"| sed "s,$Wfolders\|\./\|\.:\|:\.,${C}[1;31;103m&${C}[0m,g" >/dev/null 2>&1
>   if [ $? -eq 0 ]; then
>       SEDOVERFLOW=false
>   else
>       MAXPATH_FIND_W=$(($MAXPATH_FIND_W-1)) #If overflow of directories, check again with MAXPATH_FIND_W - 1
>       echo "Testing $MAXPATH_FIND_W"
>   fi
> done
> echo $WF
> echo "========================================================="
> echo $Wfolders
> ```
> 
> Also the new pics are really weird, could you try to reboot your system, redownload the new version and try again? xD
redownload still has this problem. Sorry i can't reboot right now.

**Comment by dmknght** [comment]
I think this commit might create this problem https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/commit/a1ea7d12ff16982a706d658341ac5d13520af288

**Comment by carlospolop** [comment]
That commit only changes the colors of some dots and Titles, not the color of everything

**Comment by dmknght** [comment]
> That commit only changes the colors of some dots and Titles, not the color of everything

Imo it must be something wrong with regex text to detect keywords. I rebooted my machine and it seems better but i still see some problems
![Screenshot at 2020-04-22 18-37-13](https://user-images.githubusercontent.com/29118926/79977326-a0211800-848d-11ea-8c36-19705f0bc6e1.png)
![Screenshot at 2020-04-22 18-37-07](https://user-images.githubusercontent.com/29118926/79977342-a57e6280-848d-11ea-867b-ad170f73abc9.png)
as you can see, `-` is showing red color. I'm not sure it is an issue or you want to do that.
![Screenshot at 2020-04-22 18-37-58](https://user-images.githubusercontent.com/29118926/79977422-c646b800-848d-11ea-9d2a-62468bb31ace.png)
![Screenshot at 2020-04-22 18-38-16](https://user-images.githubusercontent.com/29118926/79977426-c777e500-848d-11ea-99e8-081f553e29d6.png)
`35` and `no` is marked red color in process check too (4 screenshots are in process check).

**Comment by carlospolop** [comment]
Ok mate, I see, so that bright green color is the regular color of your console, I thought linpeas was doing that.
Linpeas create lists dynamically. In this case it appears that in your environment the `35` and the `-` should be colored for some reason. Without having your machine I cannot see what is exactly happening but 90% sure this is because your environment.
Please, feel free to execute linpeas in other environments and check if that is also happening. I have done that and It didn't happen in any of my envs.
Feel free to reopen this issue if you find this happening in other environments or if you know what is causing this behaviour in your env.
