### ISSUE TITLE
WinPEAS - Powershell History

### ISSUE THREAD

**Issue by blacklist-arcc** [carlospolop/privilege-escalation-awesome-scripts-suite#44]
It would be awesome, if WinPEAS checks the content of the file:

$env:APPDATA\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history

Its like bash_history for powershell and contains often jucy information

**Comment by carlospolop** [comment]
Hi @blacklist-arcc,

I agree, that would be very cool. The problem here is that I'm not that expert with PowerShell so I don't know several commands/regexps to search that could be interesting.
I will definitely look into that but feel free to help creating a basic list with interesting commands.

**Comment by blacklist-arcc** [comment]
Thanks for your feedback. I think display the first 5 lines of the content if exists and print the file location should be enough. This file contains the last Powershell commands that are executed, so it should be useful looking into in a priv esc scenario like bash_history. I think no Powershell Fu is required or is there something missing I not get? Best regards, cheers.

**Comment by carlospolop** [comment]
Hi dude,
I have added this suggestion to WinPEAS, here you can see the important part of the code in WinPEAS.exe:
https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/403e249d3b83997664edb91ad81a124c8c62bd75/winPEAS/winPEASexe/winPEAS/SystemInfo.cs#L272-L279

This information will appear inside the PowerShell information and if the file exists it will appear on red. Note, that until I create a new release of WinPEAS you will need to compile the binary yourself to gather this information (sorry about that but I can create obfuscated releases every-time I add a single thing) .

Thank you very much for the suggestion, let me know if you have more!
