### ISSUE TITLE
Pea graphic doesn't render properly in tmux sessions

### ISSUE THREAD

**Issue by kgoins** [carlospolop/privilege-escalation-awesome-scripts-suite#45]
<img width="555" alt="Screen Shot 2020-04-28 at 12 26 47 AM" src="https://user-images.githubusercontent.com/14044530/80450371-fd322900-88e6-11ea-8a7a-162bd8e5b59a.png">

**Comment by carlospolop** [comment]
Hi @kgoins,

Thanks for reporting this. I have just changes the banner, could you check the new one?
