### ISSUE TITLE
[Suggestion] Enumerate 3rd Party Drivers on Windows

### ISSUE THREAD

**Issue by kazkansouh** [carlospolop/privilege-escalation-awesome-scripts-suite#52]
Hello,

Recently I noticed that looking for 3rd party drivers on windows is a bit of a kerfuffle. At least I cant see a clean way of doing this/already available scripts.

The closet I could come up with is the following:

```powershell
Get-WmiObject Win32_PnPSignedDriver | Where-Object {$_.DriverProviderName -notmatch "Microsoft"} | Select DeviceName, DriverVersion, DeviceID
```

However, it has the issue of (1) relying on WMI that the user might not have access to, and (2) it reports about signed drivers, so could ignore unsigned drivers.

Instead, I was thinking that it could be possible to use the Win32 API. Microsoft has a [simple example in `c`](https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-device-drivers-in-the-system) that should be easy to implement in `C#` by adding the needed types. Essentially, when the code runs, it outputs a list of file names correlating to the drivers loaded.

However, this would enumerate all drivers on the system. To make this list useful it would be required removed known drivers that are not of interest, i.e. Microsoft drivers that would be covered by the windows patch level. Sadly I cant see an easier way to do this than including a whitelist of Microsoft drivers, and a quick search does not reveal such a list.

I'm not sure if there is an easier way or that the information would be better covered by the SCM instead (but that could require additional permissions to interact with), but thought I'd put this suggestion here in case its of use.

**Comment by carlospolop** [comment]
Hi @kazkansouh,

Thanks for the suggestion.
I haven't run the code but I suppose we cannot filter by provider name the list of drivers given by the C code as you did in the power-shell on-liner right?
Also, would you like to try to implement it and make a push request?

**Comment by kazkansouh** [comment]
@carlospolop yep, you are correct the API I pointed out just lists the file names, and optionally the whole path of the loaded dll. As far as I can tell the additional information from tools like `driverquery` appear (I still need to check) to come from the SCM, and the meta information from the `Win32_PnPSignedDriver` WMI class comes from the digital signatures.

It might make sense to try taking the module names and reading the signatures from them. This would alleviate the need for having a whitelist of Microsoft drivers (assuming all Microsoft drivers are signed, the devil is always in the detail) and come close to the one-liner placed before without the need for WMI access.

Sure, I'll can think about putting PR together, but I still need to do some more testing of the ideas. Hopefully within a couple weeks Ill find the time to submit something.

**Comment by carlospolop** [comment]
Hey @kazkansouh,

That looks really promising. Good idea to try to filter Microsoft drivers.
If you can prepare a PR and I will merge it with the master version.

Thank you.

**Comment by carlospolop** [comment]
Hi @kazkansouh,

How is this going?

**Comment by kazkansouh** [comment]
Hello @carlospolop -- I'm currently focused working through OSCP labs at the moment. Ideally I'm waiting to come across a nice machine to develop and test the code against (so I am killing two birds in one stone :sunglasses:), if not, Ill set one up myself but that will be when I have time to look at this in more depth.

**Comment by carlospolop** [comment]
Hi @kazkansouh,

Thank you very much for the pull request. I have merged it and updated Winpeas to add colours to the output (file and folder permissions of the drivers are now checked).
I have also created a new release (Winpeasv1.1) where the new functionality is working.
Thank you again, and let me know if you have more ideas!

**Comment by kazkansouh** [comment]
The changes look good - that's a nice idea to check permissions.
