### ISSUE TITLE
Legend typo

### ISSUE THREAD

**Issue by CarterMcKelvain** [carlospolop/privilege-escalation-awesome-scripts-suite#54]
I believe this should say "Legend" instead of "Leyend" 

https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/bd90c857407d04870e095eb0869a9987abceff2c/winPEAS/winPEASexe/winPEAS/Beaprint.cs#L81

https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/bd90c857407d04870e095eb0869a9987abceff2c/winPEAS/winPEASexe/winPEAS/Beaprint.cs#L87

**Comment by carlospolop** [comment]
Hi mate,
I have fixed it, thanks.
