### ISSUE TITLE
Scan for hidden .bat files

### ISSUE THREAD

**Issue by uBadRequest** [carlospolop/privilege-escalation-awesome-scripts-suite#59]
There is a box that has a hidden .bat script that contained the commands
```
@echo off

:LOOP

for /F "skip=6" %%i in ('net localgroup "administrators"') do net localgroup "administrators" %%i /delete

net user ausername somepassword
net user administrator someotherpassword

ping -n 3 127.0.0.1

cls

GOTO :LOOP

:EXIT
```
This appeared to have missed it.... think you could add a check for finding .bat files such as this that container credentials?

**Comment by carlospolop** [comment]
Hi @uBadRequest,

Are you proposing to search for ".bat" file only in winpeas or also in linpeas?

**Comment by carlospolop** [comment]
hello?
