### ISSUE TITLE
LinPEAS writes /tmp/shrndom with default and stealth options

### ISSUE THREAD

**Issue by revol** [carlospolop/privilege-escalation-awesome-scripts-suite#61]
Hello,

It seems like 76aa0ad9ada26a3baf23cb53efc8a5e0bd886ee1 added a new check which can lead to a file been written to disk, even when -s is provided.

https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/b7127e4a67ebb02babf1f498298d4a32adde61f7/linPEAS/linpeas.sh#L1422

**Comment by carlospolop** [comment]
Hi @revol,

Thanks for reporting the bug.
This is fixed in the last commit.
