### ISSUE TITLE
some problems for fixing

### ISSUE THREAD

**Issue by onebeht** [carlospolop/privilege-escalation-awesome-scripts-suite#70]
Thanks for fantastic script! 
My note to improve it ... linpeas v2.8.5 (on fedora 31)

1/
this should by fixed (space is misig after -E)

```
2003c2003
<       cat "$d/conf.d/filt*" | grep "path\s*=>\|code\s*=>\|ruby\s*{" | sed -E"s,path\W*=>|code\W*=>|ruby\W*\{,${C}[1;31m&${C}[0m,"
---
>       cat "$d/conf.d/filt*" | grep "path\s*=>\|code\s*=>\|ruby\s*{" | sed -E "s,path\W*=>|code\W*=>|ruby\W*\{,${C}[1;31m&${C}[0m,"
```

2/
when I start linpeas I see something like this 
```
linpeas.sh: line 257: printf: `C': invalid format character
```
it is good to see it? 

3/
```
[+] Unmounted file-system?
[i] Check if you can mount umounted devices
sed: -e expression #1, char 40: unknown option to `s'
```

4/ problem with \n
```
[+] Searching Wordpress wp-config.php files
wp-config.php files found:\n/....../wordpress/wp-config.php
```

**Comment by carlospolop** [comment]
Hi @onebeht,

Thank you for reporting these bugs.
I think the numbers 1 and 4 are now fixed.
I need to check bugs number 2 and 3 inside a fedora machine to see why is this happening.
Let me know if you figure out why are bugs 2 or 3 happening.

**Comment by carlospolop** [comment]
Hi @onebeht,

This should be fixed now.
Let me know if you that something isn't fixed yet or if you find any other error.
Thank you!

**Comment by onebeht** [comment]
Hi Carlos
I was checking Version 2.9.0

2/ still there
`Starting linpeas. Caching Writable Folders..../bin/linpeas.sh: line 257: printf: `C': invalid format character`

3/ still there
```
[+] Unmounted file-system?
[i] Check if you can mount umounted devices
sed: -e expression #1, char 40: unknown option to `s'
```
