### ISSUE TITLE
Detect invisible crontab entries

### ISSUE THREAD

**Issue by hfz1337** [carlospolop/privilege-escalation-awesome-scripts-suite#71]
The current [linpeas.sh](https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/master/linPEAS/linpeas.sh) script does not find and parse _invisible_ crontab entries. An attacker could install a somewhat invisible crontab entry by adding a carriage return after that malicious entry, then hiding it using the next line that should be longer or the same length as the malicious one. By removing the carriage return, we can make the malicious entry visible so that the script shows it to the user. The following screenshot explains the idea:

![hide_crontab_entry](https://user-images.githubusercontent.com/32499116/96352940-8e78a000-10bf-11eb-98b5-77754cad1c91.png)

On the left hand side is what the script currently does to find out which crontab entries are installed.
On the other side is what the script should do to uncover hidden crontab entries. 

In this example, the attacker would have added his malicious entry followed by a space, a hash mark (__#__) and finally the carriage return after which comes the next line. (notice that we don't put a line feed character here (__\n__) as this will render the trick useless)
The purpose of adding the hash mark is to comment out the carriage return so that it doesn't get interpreted by the shell and ruins the command.

To fix this, we remove the carriage return byte from the output before parsing it. This could help in a scenario where the system got backdoored using a covert cron job.

This was inspired from a story that happened in DEFCON finals.

**Comment by carlospolop** [comment]
This is quiet an interesting behaviour, thanks for sharing.
