### ISSUE TITLE
Not detecting password in PHP config file

### ISSUE THREAD

**Issue by cJay-c** [carlospolop/privilege-escalation-awesome-scripts-suite#74]
Tried this on TryHackMe DailyBugle box. Script did not detect password in /var/www/html/configuration.php file. Odd because all the old writeups mention about the script detecting this password.

**Comment by carlospolop** [comment]
Hi @cJay-c,

Thank you for report this bug.
Can you confirm that you are using the latest version?
Also, could you share the file or at least the line where the password appear inside the file so I can reproduce the conditions on my VM?

**Comment by cJay-c** [comment]
Yes. I am using the latest version available

var/www/html/configuration.php file contains the following password line among other parameters.

`<?php>
class JConfig {
pubic $password = 'xxxxxxxxxxxxx';
}`

**Comment by carlospolop** [comment]
Hey @cJay-c,

In the following images you can see that the last version of linpeas is correctly finding your file.

![image](https://user-images.githubusercontent.com/17181413/97117451-c0ab8280-16fb-11eb-9b2f-0837f4c5405c.png)

![image](https://user-images.githubusercontent.com/17181413/97117455-c86b2700-16fb-11eb-99f8-0f0181f3f3b8.png)

Could you recheck inside the vuln machine using the last version of linpeas?

**Comment by carlospolop** [comment]
Close due to inactivity (and because I think it's fixed)
