### ISSUE TITLE
Option to skip "find" on network shares

### ISSUE THREAD

**Issue by SQ-SEN** [carlospolop/privilege-escalation-awesome-scripts-suite#77]
An option to exclude network shares from all find commands would be useful as those can be extremely time consuming. Yes, it will miss potentially dangerous files but it'll be a lot faster and a lot less discussion with the storage guys.

**Comment by carlospolop** [comment]
Do you mean the check from Winpeas where it lists the network shares of the current machine?

**Comment by carlospolop** [comment]
Closed due to inactivity.
Please, feel free and give a more details description of the suggested change.

**Comment by Wouterkoorn** [comment]
I'd like to reopen this, as I'm having the same issues. In my case linpeas, but I guess it also applies to winpeas.

I'm running linpeas on hosts with gigantic network shares mounted, which would take forever and cause a lot of traffic.

Ideally we add an argument to exclude one or multiple folders.
