### ISSUE TITLE
Fixed the link with the Telegram group in all readme’s

### ISSUE THREAD

**Issue by alphaO4** [carlospolop/privilege-escalation-awesome-scripts-suite#78]
I fixed all the Readme.md files where the Telegramm group links where displayed wrong. 
but I can’t upload them since GitHub wont allow it.

**Comment by carlospolop** [comment]
Hi mate,

What do you mean? The links are correctly pointing to https://t.me/peass no?

**Comment by carlospolop** [comment]
Hi mate,

What do you mean? the link seems is correct: https://t.me/peass

**Comment by alphaO4** [comment]
Yes but In the readme the link wasn’t bracketed right

Carlos Polop <notifications@github.com> schrieb am Mi. 4. Nov. 2020 um
17:08:

**Comment by carlospolop** [comment]
in which Readme?

**Comment by alphaO4** [comment]
never mind, my bad my Code editor must have mest up the display of the readmes.
I am so embarrassed
