### ISSUE TITLE
 Syntax error

### ISSUE THREAD

**Issue by yckai** [carlospolop/privilege-escalation-awesome-scripts-suite#8]
When i start this script i have this errors, the previous update work correctly.
./linpeas.sh: 968: ./linpeas.sh: Syntax error: "done" unexpected (expecting "fi")

**Comment by carlospolop** [comment]
Thank you for letting me know the error. I cannot test it at the moment but it should be fixed now.

**Comment by THuizinga** [comment]
This issue is introduced again in the latest commit

**Comment by carlospolop** [comment]
Could you check latest commit?

**Comment by THuizinga** [comment]
Fixed again, thanks!
