### ISSUE TITLE
Passwords not detected in commented lines

### ISSUE THREAD

**Issue by bharder** [carlospolop/privilege-escalation-awesome-scripts-suite#85]
I assume there's a reason why it's coded this way, but `grep -v "#"` prevents commented lines (or more accurately any lines with `#` in them) from showing even if they have `PASSWORD` in the line.  This has burned me at least once. 😄

**Comment by carlospolop** [comment]
Hi @bharder,

Could you indicate me the lines where you would like to remove that `grep`? I initially put them there in order to avoid and excess of useless information. But if there is a possibility that a password is stored there, I might think about changing that behaviour.
