### ISSUE TITLE
Feature Request - Print File Paths

### ISSUE THREAD

**Issue by MidnightSeer** [carlospolop/privilege-escalation-awesome-scripts-suite#87]
Would be nice to print the file name and path when the scripts prints out content.  Currently i re-run my own greps and compare outputs to find the files that linpeas matches on.

**Comment by carlospolop** [comment]
Hi @MidnightSeer,

I don't see why not. Please, feel free to send a pull request with the changes to echo the path of the files, or please let me know which checks are missing that because a lot of checks actually print the path before showing the information.

**Comment by MidnightSeer** [comment]
@carlospolop - my bad bro, the script is great, I read it wrong on the gitlab output and didnt realize it was dumping the user database (I thought it was printing file contents)...im closing the issue.

cheers!
