### ISSUE TITLE
tmux sessions not detected

### ISSUE THREAD

**Issue by NickTheSecurityDude** [carlospolop/privilege-escalation-awesome-scripts-suite#9]
Awesome script!!! 

I noticed tmux sessions are not detected with tmux ls but they do show with a ps aux (which the script does not check for):
```
$ tmux ls 2>/dev/null
$ tmux ls
failed to connect to server: No such file or directory
$ ps aux |grep tmux
root       1019  0.0  0.1  26476  1700 ?        Ss   08:18   0:00 /usr/bin/tmux -S /.devs/dev_sess
user1       2037  0.0  0.0  13576   920 pts/4    S+   08:19   0:00 grep --color=auto tmux
$ /usr/bin/tmux -S /.devs/dev_sess
[exited]
$ 
```
In this case user1 can connect to /usr/bin/tmux -S /.devs/dev_sess and get root access via that session.

**Comment by carlospolop** [comment]
Nice! 
Thank you so much for letting me know, I will add this to the next update (this week probably)

**Comment by carlospolop** [comment]
Hello @NickTheSecurityDude,
Now tmux using a non default socket path is discovered using `ps aux` as recommended. Also, `tmux` and `screen` will be coloured in red when the list of processes is printed.

Thank you very much for your collaboration, let me know if you have any other suggestion or find any bug.
