### ISSUE TITLE
LinPEAS - USBCreator vulnerability detection failed

### ISSUE THREAD

**Issue by smidgedy** [carlospolop/privilege-escalation-awesome-scripts-suite#90]
Hi!

Apologies if I miss the mark with this issue, I don't contribute to things too often.

I was working on a Hack the Box machine (it's live now so I won't name it) that has the Linux USBCreator D-BUS vulnerability, however LinPEAS failed to detect it. I'm not a shell scripting guru, but it appears to be related to line 984 of linpeas.sh where an integer comparison is made between two floating point numbers:

```sh
if [[ $pc_length -eq 4 && $pc_numeric -lt 0.21 ]]; then
```

On this machine, `$pc_version` was equal to `0.20` which should have passed the test and been flagged as vulnerable.

There's probably a few paths to fix this, the simplest would be to replace the integer comparison with `-lt` to a string comparison with `<` i.e. `$pc_numeric < "0.20"`, however I'm not sure if this is too lazy for your tastes. I've done a pull request that instead breaks the version apart into major and minor numbers and does integer comparisons on these.

I hope this is useful - let me know if I can provide the name of the HTB machine for easy testing.

**Comment by carlospolop** [comment]
Hi @smidgedy,
I actually was looking for some time to fix this issue, so thank you very much for your pull request.

**Comment by smidgedy** [comment]
<3 thanks for the tool, I'm a filthy casual and I'd miss so much stuff without it!

**Comment by carlospolop** [comment]
Don't worry! could you confirm that the current implementation is working?

**Comment by smidgedy** [comment]
All tested and working under `/bin/sh`. I also reset my instance on HTB and re-tested with a clean version - looking good thanks again.
