### ISSUE TITLE
loops on IOT device 

### ISSUE THREAD

**Issue by Darkcast** [carlospolop/privilege-escalation-awesome-scripts-suite#93]
I am trying to run this on a IOT device with r/w and as root and it gets tuck on caching writeable folders 

[info]
/proc/cpuinfo
Processor       : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 532.24
Features        : swp half thumb fastmult vfp edsp java
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7
Hardware        : WMT
Revision        : 0000
Serial          : 0000000000000000Linux [redacted] 2.6.32.9-default #3 Mon Aug 25 16:02:49 CST 2014 armv6l GNU/Linux

[error]
./linpeas.sh
 Starting linpeas. Caching Writable Folders..../linpeas.sh: line 212: groups: not found

**Comment by carlospolop** [comment]
Hi @Darkcast,

Please, can you set variable `MAXPATH_FIND_W` to 1 in lines 11 and 14 and try again? https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/2a81943af12b547aeea2cf5b06faea757fd197cd/linPEAS/linpeas.sh#L11-L14

**Comment by Darkcast** [comment]
sure, ill check do it today and let you know. thanks for the prompt reply carlos 👍

**Comment by Darkcast** [comment]
did the changes got the stuck in the same place 
/tmp # ./linpeas.sh
 Starting linpeas. Caching Writable Folders..../linpeas.sh: line 212: groups: not found

**Comment by carlospolop** [comment]
hmmmm, unfortunately latest version of linpeas isn't invoking `groups` command in line 212, therefore it's complex to know what is going wrong.
Could you download the latest version, use it, and let me known the error? I may have an idea of what is happening but I need to confirm which line is throwing that error.

**Comment by DidierA** [comment]
Hi, please check PR #95 which should fix this problem.
